add deploy job to pipeline

diff --git a/.github/workflows/docker-build.yaml b/.github/workflows/docker-build.yaml
--- a/.github/workflows/docker-build.yaml
+++ b/.github/workflows/docker-build.yaml
@@ -1,10 +1,11 @@
-name: Build and push Docker image to ECR
+name: Build and Deploy
 on:
   push:
     branches:
       - main
     paths:
         - 'app/**'
+        - '!k8s/apps/**'
 
   workflow_dispatch:
     
@@ -18,12 +19,16 @@ concurrency:
     cancel-in-progress: true
 
 jobs:
+
     build-and-push:
         runs-on: ubuntu-latest
 
         permissions:
             contents: read
             id-token: write
+
+        outputs:
+            image_uri: ${{ steps.set-image.outputs.image_uri }}
 
         steps:
         - name: Checkout code
@@ -69,14 +74,44 @@ jobs:
             severity: CRITICAL
 
         - name: Tag and Push Docker image
+          id: set-image
           run: |
             IMAGE_URI=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.tag.outputs.IMAGE_TAG }}
             docker tag local-image:scan "$IMAGE_URI"
             docker push "$IMAGE_URI"
-            echo "$IMAGE_URI" > image-uri.txt
+            echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
 
-        - name: Upload image URI as artifact
-          uses: actions/upload-artifact@v4
+    deploy:
+        needs: build-and-push
+        runs-on: ubuntu-latest
+
+        permissions:
+            contents: write
+
+        steps:
+        - name: Checkout code
+          uses: actions/checkout@v4
           with:
-            name: image-uri
-            path: image-uri.txt
+            ref: main
+
+        - name: Update deployment
+          run: |
+            IMAGE_URI="${{ needs.build-and-push.outputs.image_uri }}"
+
+            if [ -z "$IMAGE_URI" ]; then
+              echo "Error: IMAGE_URI is empty. Exiting."
+              exit 1
+            fi
+
+            sed -i "s|image .*|image: ${IMAGE_URI}|" k8s/apps/deployment.yaml
+
+        - name: Commit and push changes
+          run: |
+            IMAGE_URI="${{ needs.build-and-push.outputs.image_uri }}"
+
+            git config --global user.name "github-actions[bot]"
+            git config --global user.email "github-actions[bot]@users.noreply.github.com"
+
+            git add k8s/apps/deployment.yaml
+            git commit -m "Update deployment image to ${IMAGE_URI}" || echo "No changes to commit"
+            git push
